name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Enhancement'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'cleanup'
      - 'merge'
  - title: '📖 Documentation'
    labels:
      - 'docs'
exclude-labels:
  - 'skip-changelog'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

autolabeler:
  - label: 'enhancement'
    branch:
      - '/^feature[/-].+/'
  - label: 'bug'
    branch:
      - '/^bug[/-].+/'
  - label: 'chore'
    branch:
      - '/^chore[/-].+/'
  - label: 'cleanup'
    branch:
      - '/^cleanup[/-].+/'
  - label: 'docs'
    branch:
      - '/^docs[/-].+/'
  - label: 'skip-changelog'
    branch:
      - '/^release[/-].+/'